VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "TestingInstance"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Property Get Name() As String
    
End Property

Public Property Get Path() As String
    
End Property
Public Property Get Process() As Process
    
End Property
Public Property Get Thread() As Thread
    
End Property
Public Property Get ExecutableName() As String
    
End Property

Public Property Get Version() As Long
    
End Property
Public Property Get VersionString() As String
    
End Property
Public Property Get MajorVersion() As Long
    
End Property
Public Property Get MinorVersion() As Long
    
End Property
Public Property Get Revision() As Long
    
End Property
Public Property Get Author() As String
    
End Property
Public Property Get Copyright() As String
    
End Property

Public Property Get CurrentLanguage() As MintAPI.Language
    
End Property

Public Property Get Application() As MintAPI.IApplication
    
End Property
Public Property Get API() As MintAPI.API
    
End Property
