VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Algorithms"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
'@PROJECT_LICENSE

Option Base 0
Option Explicit
Const CLASSID As String = "Algorithms"
Const CLASSALIAS As String = APPLICATIONDOMAIN & "." & CLASSID
Const CLASSVERSIONSTRING As String = "0.1"
Const CLASSALIASSTRING As String = CLASSALIAS & "/" & CLASSVERSIONSTRING


Implements IAliasable


Friend Sub Initialize(Optional Arguments)
    
End Sub

Public Function BinarySearch() As Variant
    
End Function
Public Function LinearSearch() As Variant
    
End Function
Public Function AutoSearch() As Variant
    
End Function

Public Function InsertionSort() As Variant
    
End Function
Public Function SelectionSort() As Variant
    
End Function
Public Function QuickSort() As Variant
    
End Function



Public Function CalculateCircleRadius() As Long
    
End Function

Public Function GetNearestPath()
    
End Function

Public Function IsPointInPath() As Boolean
    
End Function
Public Function IsPointInCircle() As Boolean
    
End Function
Public Function IsPointInOval() As Boolean
    
End Function
Public Function IsPointInCube2D() As Boolean
    
End Function
Public Function RoundPathEdges()
    
End Function

Public Function Integral() As String
    
End Function

Private Property Get IAliasable_Alias() As String
    IAliasable_Alias = CLASSALIASSTRING
End Property
