VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Cookie"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

Public Function GetCookie(strCookieName As String) As String
    
End Function
Public Sub SetCookie(strCookieName As String, strValue As String)
    
End Sub

Public Property Get Cookie(strCookieName As String) As String
    
End Property
Public Property Let Cookie(strCookieName As String, Value As String)
    
End Property

Public Sub ClearCookies()
    
End Sub
Public Sub RestartCookies()
    
End Sub

Public Property Get Count() As Long
    
End Property

Public Property Get Response() As Response
    
End Property
Public Property Get Request() As Request
    
End Property
